# Generated by Django 5.2.7 on 2025-10-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_tag_note_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="laatst bijgewerkt op"
            ),
        ),
    ]
