# Generated by Django 5.2.7 on 2025-10-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.AddField(
            model_name="note",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-vriendelijke unieke naam gebaseerd op de titel.",
                max_length=220,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="notes.tag"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
