# Generated by Django 5.2.7 on 2025-10-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_note_options_alter_tag_options_note_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-vriendelijke unieke naam gebaseerd op de titel.",
                max_length=220,
                unique=True,
            ),
        ),
    ]
