# Generated by Django 5.2.7 on 2025-10-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_alter_note_options_alter_tag_options_note_is_public_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-updated_at", "-created_at", "title"],
                "verbose_name": "notitie",
                "verbose_name_plural": "notities",
            },
        ),
    ]
